"""Informe HTML autocontenido a partir de un `ScanResult`.

Todo el contenido dinámico (detalles, hosts, payloads reflejados…) se escapa con
`html.escape`: un escáner que detecta XSS no puede, irónicamente, inyectar en su
propio informe los payloads que encuentra. El HTML lleva el CSS embebido para
poder abrirlo o compartirlo como un único archivo.
"""

import html
from datetime import datetime, timezone

from .types import Finding, ScanResult

_CSS = """
:root { color-scheme: light dark; }
body { font: 15px/1.5 system-ui, sans-serif; margin: 0; padding: 2rem;
       background: #0f1115; color: #e6e6e6; }
h1 { margin: 0 0 .25rem; font-size: 1.6rem; }
.meta { color: #8b93a1; margin-bottom: 1.5rem; font-size: .9rem; }
.summary span { display: inline-block; margin-right: 1rem; font-weight: 600; }
.high { color: #ff5c5c; } .medium { color: #ffb454; } .low { color: #5cc8ff; }
table { border-collapse: collapse; width: 100%; margin-top: 1rem; }
th, td { text-align: left; padding: .6rem .8rem; border-bottom: 1px solid #262a33;
         vertical-align: top; }
th { color: #8b93a1; font-size: .8rem; text-transform: uppercase; letter-spacing: .04em; }
.badge { display: inline-block; padding: .1rem .5rem; border-radius: 999px;
         font-size: .75rem; font-weight: 700; }
.badge.high { background: #3a1414; } .badge.medium { background: #3a2c14; }
.badge.low { background: #14283a; }
.detail { color: #c4c9d4; }
.payload { font-family: ui-monospace, monospace; font-size: .85rem; color: #8b93a1;
           word-break: break-all; }
.error { color: #ff5c5c; font-weight: 600; }
.empty { color: #6ee7a8; font-weight: 600; }
""".strip()


def _finding_title(finding: Finding) -> str:
    return (
        finding.get("header")
        or finding.get("path")
        or finding.get("param")
        or finding.get("host")
        or finding.get("method")
        or finding.get("type", "")
    )


def _document(*, body: str, generated: str) -> str:
    return (
        "<!doctype html>\n"
        '<html lang="en">\n<head>\n'
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "<title>vulnscan report</title>\n"
        f"<style>{_CSS}</style>\n"
        "</head>\n<body>\n"
        f"{body}\n"
        f'<p class="meta">Generated by vulnscan · {generated}</p>\n'
        "</body>\n</html>\n"
    )


def _findings_table(findings: list[Finding]) -> str:
    rows = []
    for f in findings:
        severity = f.get("severity", "")
        payload = f.get("payload")
        payload_cell = f'<div class="payload">{html.escape(payload)}</div>' if payload else ""
        badge = (
            f'<span class="badge {html.escape(severity)}">{html.escape(severity.upper())}</span>'
        )
        detail = f'<span class="detail">{html.escape(f.get("detail", ""))}</span>'
        rows.append(
            "<tr>"
            f"<td>{badge}</td>"
            f"<td>{html.escape(_finding_title(f))}</td>"
            f"<td>{detail}{payload_cell}</td>"
            "</tr>"
        )
    return (
        "<table>\n<thead><tr><th>Severity</th><th>Finding</th><th>Detail</th></tr></thead>\n"
        "<tbody>\n" + "\n".join(rows) + "\n</tbody>\n</table>"
    )


def render_html(result: ScanResult) -> str:
    """Renderiza el informe completo de un escaneo a HTML."""
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    if "error" in result:
        url = html.escape(result.get("url", ""))
        body = (
            "<h1>vulnscan report</h1>\n"
            f'<p class="error">Error scanning {url}: {html.escape(result["error"])}</p>'
        )
        return _document(body=body, generated=generated)

    summary = result.get("summary", {"high": 0, "medium": 0, "low": 0})
    url = html.escape(result.get("url", ""))
    status = result.get("status", "")
    findings = result.get("findings", [])

    summary_html = (
        '<p class="summary">'
        f'<span class="high">{summary["high"]} high</span>'
        f'<span class="medium">{summary["medium"]} medium</span>'
        f'<span class="low">{summary["low"]} low</span>'
        "</p>"
    )

    if findings:
        findings_html = _findings_table(findings)
    else:
        findings_html = '<p class="empty">No issues found 🎉</p>'

    body = (
        "<h1>vulnscan report</h1>\n"
        f'<p class="meta">Target: {url} · HTTP {status}</p>\n'
        f"{summary_html}\n"
        f"{findings_html}"
    )
    return _document(body=body, generated=generated)
